### ISSUE TITLE
Some containers exit

### ISSUE THREAD

**Issue by PatrickWhitehouse** [davidalger/warden#470] opened 2022-01-14 13:57 UTC
I've spent a good 4-5 hours trying to figure this out, these three containers keep exiting on the m2 install.
![image](https://user-images.githubusercontent.com/15248507/149526754-54d2c4d1-a6f1-4329-8d22-d12c98fe271d.png)

I'm on a M1 mac if this makes any difference, i've no idea what to try.

**Comment by dudzio12** [comment] 2022-01-18 21:28
Well, I'm sad that the author stoped supporting this project. I hope everything is fine with him, because it has great potential. 

For now - use forked warden repo with M1 support:
https://github.com/drpayyne/warden-multi-arch

**Comment by davidalger** [comment] 2022-02-21 23:58
Duplicate of #399, #348

**Closed by davidalger** 2022-02-21 23:58 UTC
Labels: arm64
