### ISSUE TITLE
shopware6: db and user not created on the env up 

### ISSUE THREAD

**Issue by vinayshah** [davidalger/warden#355] opened 2021-04-20 13:45 UTC
on fresh system, the db user and password are not initialized and root is not able to connect to the database in result failing in creation of the sh6 env.

**Comment by snowcore** [comment] 2021-04-20 15:36
I noticed the same yesterday. It uses the default password `app`.

**Comment by davidalger** [comment] 2021-04-20 22:40
What method were you using for install and what errors were encountered? Using `psh.phar` as outlined here https://github.com/davidalger/warden/issues/173 worked, and the db startup shouldn't have changed since then.

As has been pointed out, there are default values of `app` [in here](https://github.com/davidalger/warden/blob/develop/environments/includes/db.base.yml#L10-L14) and the databases used by shopware [are created over here](https://github.com/davidalger/warden/blob/develop/environments/shopware/db.base.yml#L9-L10).

Not having a different user/pass per environment type was by design (Magento being the exception due to historical reasons, as changing it now would break configs in existing projects), so unless there is a good reason to change this now it doesn't seem to me there is a real issue here.

**Comment by davidalger** [comment] 2021-04-22 19:49
Closing as unreproducable. Feel free to open a new issue with more details on the process used to setup, errors encountered, etc. Setup of a new env using `psh.phar` works as expected with existing environment definitions.

**Closed by davidalger** 2021-04-22 19:49 UTC
