### ISSUE TITLE
Warden Sync/Mutagen never completes pause/resume

### ISSUE THREAD

**Issue by navarr** [davidalger/warden#254] opened 2020-10-26 18:32 UTC
Issue created for tracking and Knowledge-base.

On Mac OS X with Docker Desktop 2.3.0.5 or 2.4.0.0, Warden Sync cannot pause or resume - it hangs indefinitely.

To resolve, please downgrade Docker Desktop to 2.3.0.4.

**Comment by davidalger** [comment] 2020-10-27 15:25
Duplicate of #235 

> ~To resolve, please downgrade Docker Desktop to 2.3.0.4.~

Upgrade Mutagen to 0.11.8 or later.

**Closed by davidalger** 2020-10-27 15:25 UTC
Labels: duplicate
