### ISSUE TITLE
Can possible to config disable varnish elasticsearch and rabbitmq in default run 

### ISSUE THREAD

**Issue by mrtuvn** [davidalger/warden#112] opened 2020-03-09 12:21 UTC
For frontend area i think we don't need that if we can disable such services above will save more resources

**Comment by davidalger** [comment] 2020-03-10 13:51
@mrtuvn I'm a little confused with what you mean by "for frontend area" — are you running a PWA Studio project in the containers? Magento 2 frontend frequently uses Elasticsearch for parts of the catalog.

This is a duplicate of #98 which has a PR #105 in progress currently. So probably just wait it out, but thank you for the suggestion. In the meantime, if you don't want to use varnish, you can bypass it by setting `BYPASS_VARNISH=true` in the `.env` file of a project.

**Comment by mrtuvn** [comment] 2020-03-10 14:55
my role sometime need work around with frontend theme with minimal setup
php apache/nginx db for local dev quick and no need too much cache layer . Currently very happy with your stack provide in this repo

**Closed** 2020-03-10 16:34 UTC
Labels: duplicate
