### ISSUE TITLE
Access denied to db

### ISSUE THREAD

**Issue by jajajaime** [davidalger/warden#269] opened 2020-12-04 22:15 UTC
New to warden and trying it out. I ran into an issue after setting up a Magento 2 environment, where I can't connect, import, or connect via sequelpro to the database. I get `Access denied`.
```
% warden version
0.9.1

% warden env ps
           Name                         Command               State    Ports
------------------------------------------------------------------------------
project_db_1          docker-entrypoint.sh mysql ...   Up      3306/tcp
project_nginx_1       /bin/sh -c envsubst '${NGI ...   Up      80/tcp
project_php-debug_1   docker-entrypoint php-fpm        Up      9000/tcp
project_php-fpm_1     docker-entrypoint php-fpm        Up      9000/tcp
project_redis_1       docker-entrypoint.sh redis ...   Up      6379/tcp

% warden db connect
ERROR 1045 (28000): Access denied for user 'magento'@'localhost' (using password: YES)
ERROR: Command `"${WARDEN_DIR}/bin/warden" env exec db mysql -u"${MYSQL_USER}" -p"${MYSQL_PASSWORD}" --database="${MYSQL_DATABASE}" "${WARDEN_PARAMS[@]:1}" "$@"` at /usr/local/Cellar/warden/0.9.1/commands/db.cmd:31 failed with exit code 1
```
Restarting the env or svc does not fix the issue.

I am on macOS 10.15.7 and Docker Desktop 2.5.0.1

**Comment by jajajaime** [comment] 2020-12-04 22:37
Looks like restarting Docker Desktop did the trick somehow. Not sure what fixes it with that. First run issues?

**Comment by jantzenw** [comment] 2020-12-08 21:55
Probably https://github.com/davidalger/warden/issues/260

**Comment by davidalger** [comment] 2020-12-12 18:44
@jajajaime Glad you find a way around the issue. Going to close it out since it looks like it's resolved for you. To add a bit of context though, the reference to issue 260 would NOT be related, as `warden db connect` does not use the ssh tunnel, it uses `docker exec`. The command will be using the MYSQL_PASSWORD value embedded in the docker-compose configuration (you can see this by running `warden env config | grep -i mysql_password`) and might fail if that value was changed and the mysql container wasn't re-initialized as the docker container's entrypoint script only creates the user on first startup of the container. Not sure that applies given you're new to warden though and I'm not guessing you tried to change the mysql pw.

**Closed by davidalger** 2020-12-12 18:44 UTC

**Comment by jaybeckr** [comment] 2021-01-05 00:35
I ran into the same thing, which was caused by the fact that I set warden up on a project that I had used with another docker container management tool so there was an existing `<project>_db_1` that wound up getting re-used by warden.

To get around this, I stopped, removed, and had warden re-create the container:
```
docker stop <project>_db_1
docker rm <project>_db_1
warden env up
```

**Comment by Ohopwood** [comment] 2022-01-28 18:40
I'm running into a similar issue:

warden version: 0.12.0
Docker Desktop: Docker Desktop 4.4.2
Mac OS: 12.1
 
 I am able to connect using warden cli
![Project-warden-db-connect](https://user-images.githubusercontent.com/2118703/151602835-d0b90a14-89ff-4b1b-8a93-4c2c33e63d4b.png)
 But, i'm unable trying to connect using phpstorm, 

`Could not connect to address=(host=project_db_1)(port=3306)(type=master) : Socket fail to connect to host:project_db_1, port:3306. project_db_1.`

Restarting the Docker, removing, and rebuilding did not resolve the issue.
