### ISSUE TITLE
Possibility to uninstall Warden completely

### ISSUE THREAD

**Issue by drpayyne** [davidalger/warden#440] opened 2021-10-28 09:27 UTC
Is there a way to uninstall Warden completely including the certs it installed, the configs it set in the system, etc. Maybe we need a command like `warden uninstall`?

**Comment by drpayyne** [comment] 2022-01-26 13:34
yep

**Comment by davidalger** [comment] 2022-02-15 16:29
Duplicate of #183

**Closed by davidalger** 2022-02-15 16:29 UTC
